In [1]:
import numpy as np

1. How to Creating a 3x3 Identity Matrix with Float Data Type?

In [3]:
array1 = np.array([[11,12,13],[14,15,16],[17,18,19]], dtype=float)
print(array1)

[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]


2. Create a 1D Array with Random Values between 0 and 1.

In [6]:
array2 = np.random.rand(8)
print(array2)

[0.25209292 0.74778642 0.54746966 0.47427411 0.15269482 0.28666118
 0.13836938 0.59673239]


3. Create a 2D Array with Random Integer Values.

In [9]:
array3 = np.random.randint(0,100,size=(2,3))
print(array3)

[[ 0 75 28]
 [93 14 50]]


4. Creating an Array Using a Custom Function.

In [11]:
def custom_func(i,j):
    return i+j
array = np.fromfunction(custom_func,(3,4),dtype=int)
print(array)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


5. Reshaping a 1D Array into a 2D Array.

In [14]:
array1 = np.arange(12)
array2 = array1.reshape(3,4)
print(array1)
print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


6. How to Creating a 3x3 Array of Ones?

In [16]:
array = np.ones((3,3))
print(array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


7. How to get the common items between two pythons 
NumPy? Input: 
a = np. array ([1,2,3,2,3,4,3,4,5,6]) 
b = np. array ([7,2,10,2,7,4,9,4,9,8]) 
Expected Output: 
array ([2, 4])

In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a,b)
print(common)

[2 4]


8. From array a remove all items present in 
array b Input: 
a = np. array ([1,2,3,4,5]) 
b = np. array ([5,6,7,8,9]) 
Expected Output: 
array ([1,2,3,4]

In [19]:
a = np. array ([1,2,3,4,5]) 
b = np. array ([5,6,7,8,9])
result = np.setdiff1d(a,b)
print(result)

[1 2 3 4]


9. Limit the number of items printed in python NumPy array a to a maximum of 
6 elements. 
a = np. arrange (15) 
Expected Output: 
array ([ 0, 1, 2, ..., 12, 13, 14]

In [21]:
a = np.arange (15)
np.set_printoptions(threshold = 6)
print(a)

[ 0  1  2 ... 12 13 14]


10. Drop all nan values from a 1D NumPy 
array Input: 
np. array ([1,2,3, np.nan,5,6,7, np.nan]) 
Desired Output: 
array ([ 1., 2., 3., 5., 6., 7.])

In [23]:
arr = np. array ([1,2,3, np.nan,5,6,7, np.nan])
clean_arr = arr[~np.isnan(arr)]
print(clean_arr)

[1. 2. 3. 5. 6. 7.]


11. Question: Create a 1D NumPy array of the first 20 natural numbers and a 
2D NumPy array of shape (4, 5) with values ranging from 1 to 20.

In [24]:
array1 = np.arange(1,21)
print("1D array:")
print(array1)

array2 = np.arange(1,21).reshape(4,5)
print("2D array:")
print(array2)

1D array:
[ 1  2  3 ... 18 19 20]
2D array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


12. Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, 
number of dimensions, and data type. Change its data type to float64 and verify 
the change.

In [25]:
array = np.arange(24).reshape(2,3,4)
print(array)
print(array.shape)
print(array.size)
print(array.ndim)
print(array.dtype)

array_float = array.astype(np.float64)
print(array_float.dtype)
print(array_float)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
24
3
int64
float64
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


13. Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then 
flatten it back into a 1D array using ravel (). Verify that the flattened array 
matches the original

In [3]:
original_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Original 1D Array:",original_array)

reshaped_array = original_array.reshape(3,4)
print("\nReshaped 2D Array (3X4)")
print(reshaped_array)

flattened_array = reshaped_array.ravel()
print("\nFlattened Array using ravel():")
print(flattened_array)

is_equal = np.array_equal(original_array,flattened_array)
print("\nDoes the flattened array match the original? -> ", is_equal)

Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 2D Array (3X4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened Array using ravel():
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Does the flattened array match the original? ->  True


14. Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4, 
5, 6]), perform element-wise addition, subtraction, multiplication, and 
division. Explain the behavior when dividing by zero.

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b
a - b
a * b
a / b

array([0.25, 0.4 , 0.5 ])

In [7]:
#Division by Zero Behavior:
#Dividing by an array that has zero:
c = np.array([1,0,3])
a / c
# Numpy does not raise an error when dividing by zero.
# It returns inf (infinity) or nan (not a number) where appropriate.
# It also raises a warning, which can be suppressed or handled if needed.

C:\Users\PURVI PAWAR\AppData\Local\Temp\ipykernel_664\1060672576.py:4: RuntimeWarning: divide by zero encountered in divide
  a / c


array([ 1., inf,  1.])